### ISSUE TITLE
Exception thrown in 'Document This': Could not find file: 'c:/administrator/work/sell/src/components/shopcart/shopcart.vue'.

### ISSUE THREAD

**Issue by cqgsm** [joelday/vscode-docthis#104]
Platform: win32

Steps to reproduce the error:

Code excerpt that reproduces the error (optional):

Exception:
{"name":"Error","message":"Could not find file: 'c:/administrator/work/sell/src/components/shopcart/shopcart.vue'.","stack":"Error: Could not find file: 'c:/administrator/work/sell/src/components/shopcart/shopcart.vue'.\n    at getValidSourceFile (C:\\Users\\caoqi\\.vscode\\extensions\\joelday.docthis-0.3.9\\node_modules\\typescript\\lib\\typescript.js:78776:23)\n    at Object.getSyntacticDiagnostics (C:\\Users\\caoqi\\.vscode\\extensions\\joelday.docthis-0.3.9\\node_modules\\typescript\\lib\\typescript.js:78983:52)\n    at Documenter._getSourceFile (C:\\Users\\caoqi\\.vscode\\extensions\\joelday.docthis-0.3.9\\out\\src\\documenter.js:177:24)\n    at Documenter.documentThis (C:\\Users\\caoqi\\.vscode\\extensions\\joelday.docthis-0.3.9\\out\\src\\documenter.js:46:33)\n    at runCommand (C:\\Users\\caoqi\\.vscode\\extensions\\joelday.docthis-0.3.9\\out\\src\\extension.js:110:24)\n    at runCommand (C:\\Users\\caoqi\\.vscode\\extensions\\joelday.docthis-0.3.9\\out\\src\\extension.js:66:9)\n    at context.subscriptions.push.vs.commands.registerTextEditorCommand (C:\\Users\\caoqi\\.vscode\\extensions\\joelday.docthis-0.3.9\\out\\src\\extension.js:109:9)\n    at c:\\administrator\\software\\vscode\

**Comment by joelday** [comment]
@cqgsm Please update to the latest version. Thanks!
