### ISSUE TITLE
Exception thrown in 'Document This': Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by akram1905** [joelday/vscode-docthis#109]
Platform: win10x64

Steps to reproduce the error:
pressing Ctrl+Alt+D twice produce  the error only first time I use it.
Second time (pressing Ctrl+Alt+D twice) works.

Code excerpt that reproduces the error (optional):

Exception:
{"name":"TypeError","message":"Cannot read property 'text' of undefined","stack":"TypeError: Cannot read property 'text' of undefined\n    at NodeObject.createChildren (C:\\Users\\akram\\.vscode\\extensions\\joelday.docthis-0.3.11\\node_modules\\typescript\\lib\\typescript.js:79749:72)\n    at NodeObject.getChildren (C:\\Users\\akram\\.vscode\\extensions\\joelday.docthis-0.3.11\\node_modules\\typescript\\lib\\typescript.js:79801:22)\n    at findChildFunc (C:\\Users\\akram\\.vscode\\extensions\\joelday.docthis-0.3.11\\out\\src\\utilities.js:55:11)\n    at Array.forEach (native)\n    at findChildFunc (C:\\Users\\akram\\.vscode\\extensions\\joelday.docthis-0.3.11\\out\\src\\utilities.js:55:25)\n    at Array.forEach (native)\n    at findChildFunc (C:\\Users\\akram\\.vscode\\extensions\\joelday.docthis-0.3.11\\out\\src\\utilities.js:55:25)\n    at Array.forEach (native)\n    at findChildFunc (C:\\Users\\akram\\.vscode\\extensions\\joelday.docthis-0.3.11\\out\\src\\utilities.js:55:25)\n    at Array.forEach (native)"}

**Comment by joelday** [comment]
Dupe of #73
