### ISSUE TITLE
Shortcuts colliding

### ISSUE THREAD

**Issue by csholmq** [joelday/vscode-docthis#11]
From README.md:

```
Windows: Ctrl-Shift-D Ctrl-Shift-D
Windows: Ctrl-Shift-D Ctrl-Shift-E
Windows: Ctrl-Shift-D Ctrl-Shift-V
```

From Default Keyboard Bindings:

```
{ "key": "ctrl+d ctrl+d",         "command": "docthis.documentThis" },
{ "key": "ctrl+d ctrl+e",         "command": "docthis.documentEverything" },
{ "key": "ctrl+d ctrl+v",         "command": "docthis.documentEverythingVisible" },
```

This **collides with ctrl+d** which is the built in `editor.action.addSelectionToNextFindMatch`

**Comment by joelday** [comment]
Thanks! I'll switch it around to reflect what I had (inadvertently) in the README.md.

**Comment by joelday** [comment]
@csholmq Let me know if this collides with any of your other extensions.

**Comment by csholmq** [comment]
No collision. But also no handler => No go :-1:

**Comment by elcojacobs** [comment]
Would it be possible to add a user setting to configure the shortcut?
CTRL-ALT-D collides with switching desktops on Ubuntu Gnome.

**Comment by TheOpenDevProject** [comment]
@elcojacobs I will look into this. Should be possible as VSCode allows for pretty advanced user configs.

**Comment by joelday** [comment]
@elcojacobs Could you suggest an alternative? I'm not sure what the best option is. Thanks!

**Comment by elcojacobs** [comment]
I just did some more googling when I got your message and looks like customizing the shortcut is already possible!

If you go to File -> Preferences -> Keyboard Shortcuts, you can edit `User/keybindings.json`

I mapped mine to `ctrl-alt-/`

``` javascript
// Place your key bindings in this file to overwrite the defaults
[
  { "key": "ctrl+alt+/ ctrl+alt+/", "command": "docthis.documentThis" },
  { "key": "ctrl+alt+/ ctrl+alt+e", "command": "docthis.documentEverything" }
]
```

So I suggest adding this to the docs and closing this issue :+1: No further action needed.

**Comment by TheOpenDevProject** [comment]
Thanks,  I will add this to the docs today. 

Closing.
