### ISSUE TITLE
Object arguments

### ISSUE THREAD

**Issue by edDimensi** [joelday/vscode-docthis#111]
It does not show the object arguments
```
/**
 * 
 * 
 * @export
 * @param {Object} options 
 * @param {Node} options.target
 * @param {Node} options.parent
 * @param {string} options.propertyName
 * @param {number} options.units
 * @param {number} options.divider
 * @param {Function} options.onInput
 */
export function initControl(options) {
	const { target, parent, propertyName, units, divider, onInput } = options;
        ...
}
```

![image](https://cloud.githubusercontent.com/assets/11390039/23146724/46687688-f7ea-11e6-802c-01182807c139.png)

After reload vs code, now display that 
![image](https://cloud.githubusercontent.com/assets/11390039/23146827/4cddd2b4-f7eb-11e6-86c9-8069416a7151.png)
But this is not what is normally displayed

**Comment by joelday** [comment]
There are a few things going on here to look into. Will come back to this as soon as I can.

**Comment by joelday** [comment]
DocThis doesn't generate the object property notation, but that's a feature that should be added when the structure of that type is known. As for the behavior of the TypeScript language service, I can't really speak to that. Can you produce an example where it works properly?

**Comment by joelday** [comment]
Your notation looks correct, so I'm going to say this is external to the VSCode TypeScript language service. I added #112 for tracking adding output of object properties as a feature.
