### ISSUE TITLE
The new version of the new bug

### ISSUE THREAD

**Issue by tomoat** [joelday/vscode-docthis#113]
vscode: 2.1.6
docthis version:0.4.0
os: macos sierra 10.12.3

The new version of the new bug,and old version does not have this bug
`/**`
Error: docthis: Failed to document at current position: Cannot read property 'kind' of null
<img width="570" alt="wx20170222-150018 2x" src="https://cloud.githubusercontent.com/assets/7428698/23200756/1676298e-f911-11e6-84a7-f378b851b7f2.png">

'Ctrl+Alt+D'
show error:
Sorry! 'Document This' wasn't able to produce documentation at the current caret position.

**Comment by bitqiang** [comment]
How do you solve the problem later?
I met this problem today, too
The version is 0.4.6
