### ISSUE TITLE
Adding a line under the first line of a block comment starts documentation

### ISSUE THREAD

**Issue by joelday** [joelday/vscode-docthis#116]
With automatic block comment documentation enabled, when the selection positioned below `/**`, entering a new-line causes documentation generation to be attempted.

**Comment by axefrog** [comment]
I'm experience this bug right now I think:

![vscode-jsdoc-enter-key-bug](https://cloud.githubusercontent.com/assets/298883/24529973/4ecdf386-15f2-11e7-97ae-7951149cd2af.gif)

**Comment by joelday** [comment]
@axefrog That's a different, external issue. Unfortunately, the snippet feature in VSCode requires you to use shift-enter/shift-return when filling out a placeholder.

It might be a good idea to have an option to disable snippets, but unfortunately that requires bringing back some of the indentation code that has been difficult to keep reliable.

**Comment by axefrog** [comment]
Ah, dang. Thanks anyway.
