### ISSUE TITLE
Unable to execute the 'Document Everything' command

### ISSUE THREAD

**Issue by rehannawab** [joelday/vscode-docthis#118]
I see that the 'ctrl+d ctrl+e' command was removed. Is there any other way to run the document everything command or was this command intentionally removed?

**Comment by joelday** [comment]
@rehannawab It was temporarily removed. Will be adding it back soon. Sorry!

**Comment by BridgeAR** [comment]
Is there any estimate when this is coming back? Or can I help to bring back this feature? If so: would you be so kind and point why your removed it?
I see that you removed it in commit 491fe0ad68db3bc3a2031a833c7212463225d900 while changing the insertion to become snippets.

**Comment by joelday** [comment]
@BridgeAR Thank you for offering to look into this. The main challenge was inserting the documentation reliably while retaining indentation. When the switch to the new Snippet API was completed, the extension now relies on it to handle the indentation logic. The caveat is that it can't be used to insert documentation multiple times all in one execution.

https://github.com/joelday/vscode-docthis/commit/b1dacffa1155321731c1cb1451671f96c5436d9c is 3.11.0, which is the last release that had the original insertion logic. There were a couple of bugs with this related to the cursor jumping incorrectly or indentation breaking.

The old logic could be restored and polished in parallel to the new Snippet based logic. This would also have the benefit of allowing users to disable Snippet insertion entirely. In retrospect, it may have been better to retain the original logic and allow users to opt out from the start.

document.ts has gotten unwieldy and my 1.0 refactor work has stalled, but document.ts has gotten pretty huge. If we're going to bring that back, we might look at how we can at least break out the actual VSCode document mutation behavior from the comment text generation. That would make maintenance of the two different insertion behaviors much easier.

I'd like to get this moving, but I'd like to get 1.0 moving again as well. I currently have that in a private repo waiting to reach a state where I can move it over to a new branch here. Any help you can offer would be massively appreciated!
