### ISSUE TITLE
FR: require CR after `/**` to trigger automatic documentation

### ISSUE THREAD

**Issue by dtgriscom** [joelday/vscode-docthis#121]
DocThis is great for documenting TypeScript functions, and I especially like its automatic generation of JSDoc blocks for methods when I type `/**`. However, I find it problematic when documenting variables. The variable definition includes all the necessary type info; all I'd be adding is an English description of its purpose. So, for compactness, I like one-line comments, e.g. `/** Enables catching fire when CPU overheats */`. But, when I start typing such a comment, DocThis leaps in and inserts a big block of (unnecessary) tags.

If instead DocThis required a `<CR>` after the `/**` before inserting the block, I could have it both ways. To generate the block I'd type `/**<CR>` and bingo: the block would be ready to go. If I wanted a one-line comment, then I could just type what I wanted without that `<CR>`, and DocThis would stay out of the way.

Yes, I could type `Control-Alt-D Control-Alt-D`, but that would disrupt my touch-typing. I'd find the additional `<CR>` would take a few milliseconds to type, and it's actually a pretty natural trigger for the action. (Given that your users are all used to getting the block without having to type `<CR>`, you'd probably want to make this an option.)

Thanks!

**Comment by joelday** [comment]
@dtgriscom I really like this idea. Unfortunately I'm slammed with other stuff right now. Can you take a peek at the subscription on https://github.com/joelday/vscode-docthis/blob/master/src/extension.ts#L48 and see if you can update the contentChanges evaluation to detect that?

Thanks!

**Comment by dtgriscom** [comment]
Interesting; I've never looked at VSC extension code before...

It looks like you're triggering on VSC automatically changing the final `*` of the typed `/**` to `* */`; is that right? If so, then you'll have to either maintain a history of actions, or do some more sophisticated analysis of the change (and what's there beforehand).

And, I, too, am slammed at the moment (yes: happy to request, unavailable for assistance...)


Thanks for thinking about it,
Dan

**Comment by joelday** [comment]
@dtgriscom Thanks for taking a look! The change matching is a bit weird. I've had to just look at the most recent change reported for the sequence and then match against it.

**Comment by dtgriscom** [comment]
Hi, Joel. I figured out how to handle this in extension.ts: 

- Set up a static var `starSpaceStarInserted: boolean`

- In `activate()`, if `change.text == '* */`, then set `starSpaceStarInserted`. Otherwise, if `starSpaceStarInserted && change.text.charAt(0) = '\r'`, then insert the documentation. (Clear `starSpaceStarInserted` at all the appropriate places.)

So, I now have the code ignoring the "/**" unless it is immediately followed by a CR. But, the inserted comment blocks are messed up, because your assumptions on where the cursor would be upon insertion are now wrong. I'd try to fix the comment generation, but I'm concerned that it might be a sinkhole.

I'm going to set this aside for now, unless you have any suggestions on how to get the comment insertion reliably right.

**Comment by joelday** [comment]
@dtgriscom A fix to #129 should handle this for us. We'd get the /** detection for free, too.

**Comment by joelday** [comment]
Thank you for digging into this!
