### ISSUE TITLE
"@type" and "@memberOf" appears on the same line.

### ISSUE THREAD

**Issue by superamadeus** [joelday/vscode-docthis#136]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0

Documenting a member of a class with a type annotation results in the `@type` and `@memberOf` declarations emitted on the same line.

**Comment by joelday** [comment]
Huge thank you for submitting a fix!
