### ISSUE TITLE
hope support @create_time or @ dev_time in this plugin

### ISSUE THREAD

**Issue by ZPOMI** [joelday/vscode-docthis#138]

**Comment by zimplexing** [comment]
and @author hope to supported

**Comment by ZPOMI** [comment]
@zimplexing 
you should config those in your settings.json
<pre><code>
  // When enabled, will add the @author tag.
  "docthis.includeAuthorTag": true,

  // When docthis.includeAuthorTag is enabled, will add @author tag with this value.
  "docthis.authorName": "pomi",
</code></pre>

**Comment by joelday** [comment]
I'm concerned about adding tags that are (at least significantly) outside of the JSDoc spec. I'd rather support this through some kind of templating support. (#119)
