### ISSUE TITLE
Switch logo to format other than SVG

### ISSUE THREAD

**Issue by JimiC** [joelday/vscode-docthis#145]
As per https://code.visualstudio.com/updates/v1_14#_extension-authoring

**Comment by joelday** [comment]
@JimiC Do you know off-hand if the VSCode team has suggested an ideal image resolution?

**Comment by JimiC** [comment]
Should be no less than 128x128 so it can show up unblurry in the marketplace and inside the `vscode` extension details panel.

**Comment by joelday** [comment]
Ergh, are they scaling to 72dpi on the marketplace regardless?

https://github.com/Microsoft/vscode-docs/issues/1101

**Comment by JimiC** [comment]
Looks like so. We use a 504x504 image which gets scaled to 128x128.

**Comment by joelday** [comment]
@JimiC Thanks!
