### ISSUE TITLE
"trailing whitespace" compilation error in typescript

### ISSUE THREAD

**Issue by christophediprima** [joelday/vscode-docthis#146]
I use it with typescript but the comments are generated with trailing whitespaces that is considered as an error for the compiler.

Is it possible to have the comments generated without these spaces?

**Comment by RanzQ** [comment]
Similar issue with eslint rule `no-trailing-spaces`. Would be easier to add spaces manually if needed.

**Comment by joelday** [comment]
@christophediprima @RanzQ Agreed. This has been annoying me, too.

**Comment by joelday** [comment]
@christophediprima @RanzQ Fixed in 0.7.0
