### ISSUE TITLE
DocumentThis not working in .vue component files between <script> tags

### ISSUE THREAD

**Issue by dannyrb** [joelday/vscode-docthis#147]
I'm using VueJS's single "Component" files. They have a `.vue` extension and contain three parts:

```
<template>
   <!-- HTML CONTENT -->
</template>

<script>
   // JS Content
</script>

<style lang="scss" scoped>
   /* Styling content */
</style>
```

When I try to use `Document This` in the JS section, I receive the following error:

> Sorry! 'Document This' wasn't able to produce documentation at the current caret position.

Moving the JS to an external `.js` file allows the plugin to work as expected.

**Comment by joelday** [comment]
Now covered by #154
