### ISSUE TITLE
Improve JavaScript support

### ISSUE THREAD

**Issue by joelday** [joelday/vscode-docthis#15]
Documentation fails in various valid scenarios.

**Comment by michaeljota** [comment]
It seems that you may use Salsa for this. I don't know if it would help, but it seems so.

**Comment by joelday** [comment]
@michaeljota Agreed! Right now it's only reading the AST, which doesn't have type checking or inference. There's a fair amount of complexity in making sure that works reliably and with adequate performance. I'd still like to do it, though.

**Comment by joelday** [comment]
Looking pretty good now. :)
