### ISSUE TITLE
Multi-root Workspaces and DocThis

### ISSUE THREAD

**Issue by seanmcbreen** [joelday/vscode-docthis#153]
Hi,

I'm from the VS Code team and I'm reaching out with some additional resources for adopting multi-root workspaces.

But first let me say thank you for working on and maintaining [Document This for VS Code](https://marketplace.visualstudio.com/items?itemName=joelday.docthis) which is one of the most popular extensions, we really appreciate the work you have done to make VS Code better.

The purpose of this issue is that we are very close to releasing a significant new feature for VS Code - Multi-root Workspaces - which is the [most requested](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request+sort%3Areactions-%2B1-desc) missing feature. If you have not heard of multi-root workspaces we have [described this in several of our recent updates](https://code.visualstudio.com/updates/v1_17#_preview-multi-root-workspaces).  Today it's only enabled in our insiders release but **our intent is to enable it for all users** in our [next update](https://github.com/Microsoft/vscode/issues/35875), targeted for release in the first week of November.

This is a pretty significant change and over the last four months we have updated pretty much all of VS Code to be Multi-root aware as well as updated all of our own extensions.  In the process of doing this we have created a set of [guidelines for Extension Authors](https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs) to follow to ensure their extension can fully leverage the awesomeness that is Multi-root workspaces.

**Our Request:**

Having looked at your extension we think changes are required in how you:

* Make use of the (now deprecated) `workspace.rootPath` property, there is a proposed migration path and sample for this case.
* Contribute or change settings, specifically you need to review whether some of the settings can be applied on a resource (= file location) level instead of being global (= workspace level).

**How Can We Help/Resources:**

We realize we are asking for your help here - our goal is to make sure that your extensions works well with multi-root and continues to be loved by the community.  [The guide above outlines the changes that are required](https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs) and we have a [samples](https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs#samples) as well.

But we are sure you will have questions and we thought one way we could look to help is by getting a number of the team members (myself included) to be ready to respond to questions on a Slack Channel that we will dedicate to this issue.  To join that channel simply [follow this link](https://vscode-dev-community.slack.com/join/shared_invite/enQtMjIxOTgxNDE3NzM0LWU5M2ZiZDU1YjBlMzdlZjA2YjBjYzRhYTM5NTgzMTAxMjdiNWU0ZmQzYWI3MWU5N2Q1YjBiYmQ4MzY0NDE1MzY).

Again thank you for being part of the VS Code community - we appreciate everything you have done.  With the release of Multi-root Workspaces we will be shipping our most requested feature, together we can really help this feature light up for users.

Happy Coding!
Sean McBreen

// cc @bpasero @mjbvz

**Comment by joelday** [comment]
@seanmcbreen Will be checking this out soon. I haven't heard of any issues from Insiders users, but use of the deprecated property should be removed nonetheless. Thanks for having such an active relationship with the extension developer community.

As a side note: I've been unable to keep up with this project as much as I think is adequate. I'd like to get an idea from the TS/VSCode teams of what the roadmap and prioritization for native JSDoc tooling is. In the long run, I think the end-user will be better off with first-class support. I'd also like to avoid competing with or overshadowing those efforts. That said, there are also niche features that vscode-docthis users have requested and implemented that I would consider feature-bloat or incomplete and I'd prefer to not leave those users in the dust.

I'm a passionate user of VSCode and I don't want users' adoption to be contingent upon an extension that doesn't receive the attention that it deserves.

**Comment by mjbvz** [comment]
@joelday I'd love to make VS Code's built-in jsdoc support better. I think this extension addresses  different use case though than what we have been targeting previously

In typescript files, the type-system itself is used as the source of truth. You can have jsdoc type annotations and annotations such as `@extends`, but TypeScript will ignore them and there is nothing to prevent them from getting out of date. When publishing a js library generated from ts, instead of using jsdocs annotations, the recommendation is to publish a d.ts file with typings information.

It seems to me that this extension is really aimed at the moving type info from the type system into jsdocs, which is a different way of doing things than the TypeScript team has aimed to support in the past

**Comment by seanmcbreen** [comment]
**Request:** if you have prepared your extension for Multi-root Workspaces we would love you to add multi-root ready to your `package.json` i.e. `"keywords": ["multi-root ready"]`. If you upgrade to `VSCE 1.32.0` this can be added to any existing keywords and will not be counted against the maximum of 5 allowed keywords.

This will help us keep track of adoptions and also help users know which extensions have been fully tested.   Remember we are here to help should you need it on the Slack channel.

Happy Coding
Sean McBreen

**Comment by joelday** [comment]
@mjbvz I agree with that. I think that at this point, the only truly valid case is to add inferred type information when writing regular JavaScript. Doing that would require having symbolic information, though and I have concerns with the complexity of running and properly configuring an instance of the language service that goes beyond looking at the AST.

Going forward, I'd like to have less emphasis on type information and better refactoring and advanced tagging support. Some of that overlaps with your functionality. Most of that is out of scope for your support.

It might make sense to shift toward extending the generated documentation *after* TypeScript does it for you, but I'm unsure of the right places to hook in for that.

**Comment by joelday** [comment]
@seanmcbreen 0.6.0 should be good. I'll try to get that tag added soon.

**Comment by seanmcbreen** [comment]
Awesome!

Yes we have a community run slack and a few of the team are in there every now and again - come on and join in :)

**Comment by joelday** [comment]
@mjbvz I'm working on moving the core of this project over to a language service plugin. It'll still be emitting (much better) type information when configured to do so, but the biggest draw is going to be advanced templating and in-place updates. Thanks!

**Comment by mjbvz** [comment]
@joelday Cool! Let me know if you have any questions about this or run into any problems
