### ISSUE TITLE
Inferred return types are not documented (TypeScript)

### ISSUE THREAD

**Issue by larssn** [joelday/vscode-docthis#159]
```
class Test {
   myMethod() {
      return 'dog';
   }
}
```

Documenting this method becomes:

```
  /**
   * 
   * 
   * @returns 
   * @memberof ChoiceDBService
   */
  myMethod() {
    return 'dog';
  }
```

Shouldn't Document This infer that the return type is a string, and mark it as such?

**Comment by joelday** [comment]
https://github.com/joelday/vscode-docthis/issues/23

**Comment by joelday** [comment]
@larssn The big challenge here is that Document This currently works by only scanning the syntax tree rather than bringing up the type system, which has a lot of complexity. I've experimented with this in the past, but there might be easier options now. Will try to revisit it.

**Comment by lukasbash** [comment]
What is the status on this? I see also #23 has been closed.
It would be super useful if we could also use inferred types in the docs.
