### ISSUE TITLE
"No handler found"

### ISSUE THREAD

**Issue by csholmq** [joelday/vscode-docthis#16]
![image](https://cloud.githubusercontent.com/assets/1297882/12898408/dbcf34fe-ceac-11e5-8bd3-db9ef89df730.png)

**Comment by joelday** [comment]
It's set to activate on JavaScript and TypeScript language load. Just to make sure, does it still happen after a document of either have been opened?

**Comment by csholmq** [comment]
Works like a charm for JS and TS.

![image](https://cloud.githubusercontent.com/assets/1297882/12900051/95c1ae6c-ceb4-11e5-835c-6088314cdb4e.png)

Any reason for not supporting other languages? E.g. C/C++ ;)

**Comment by joelday** [comment]
It's on my roadmap. :)

**Comment by joelday** [comment]
#6
