### ISSUE TITLE
[improvement] Documenting fat arrow functions that are declared using const or let

### ISSUE THREAD

**Issue by mayaro** [joelday/vscode-docthis#162]
Steps to reproduce:
1. Write a function declaration this way:
`const fun = (param1, param2) => {
    console.log(param1, param2);
};`
2. Try to add documentation for this function

I'm not sure if this was already added as a issue, but I did not manage to find it and it would be nice to have.
Can anyone confirm and give feedback for this?

**Comment by alanaasmaa** [comment]
It works when you but your cursor inside `(param1, param2)` and press the hotkey. But it does not work when returning promises and has some other issues with ES6
