### ISSUE TITLE
Add arrow functions support

### ISSUE THREAD

**Issue by TheDutchCoder** [joelday/vscode-docthis#173]
It would be nice if the plugin could support arrow functions.

Current behaviour:
```js
  /**
   * Normalizes the photos returned by the Camera Roll.
   *
   * @memberof PhotoPicker
   */
  normalizeCameraPhotos = (photos) => {
```

Requested behaviour:
```js
  /**
   * Normalizes the photos returned by the Camera Roll.
   *
   * @param {object} photos Description
   * @memberof PhotoPicker
   */
  normalizeCameraPhotos = (photos) => {
```

**Comment by TheOpenDevProject** [comment]
@joelday Didn't we look into this, I don't remember why but for some reason it was a breaking change to the way we parse the document. Ill re-investigate later in the week now im back into doing these FOSS projects.

**Comment by mukuljainx** [comment]
@TheDutchCoder, not a solution but if you will press the shortcut from 2nd line of the function it will consider params too but will miss the class (memberof).

**Comment by joelday** [comment]
Tracking this in #178
