### ISSUE TITLE
We plan to feature your VS Code extension! 

### ISSUE THREAD

**Issue by auchenberg** [joelday/vscode-docthis#174]
Hi,

It's Kenneth from VS Code. I'm reaching out to tell you that we plan to feature your awesome VS Code extension on our marketplace https://marketplace.visualstudio.com/#VSCode in the next iteration.

Please work with your community to resolve any major issues, as you'll probably see a significant bump in new users trying your extension.

Thanks for the great work, and happy coding!

/k

Kenneth Auchenberg
Visual Studio Code
Program Manager, Microsoft

**Comment by TheOpenDevProject** [comment]
@auchenberg Thanks. What date is the next iteration?.

**Comment by auchenberg** [comment]
Next week @TheOpenDevProject

**Comment by joelday** [comment]
@auchenberg Thanks a bunch! We'll see what we can get resolved before then. As always, it's super appreciated to get communications and feedback from the vscode team.

**Comment by joelday** [comment]
Thank you for featuring it!
