### ISSUE TITLE
比较low

### ISSUE THREAD

**Issue by 1824437** [joelday/vscode-docthis#175]
es5语法下，如
`
{
fn: function (){}}
`
无法/**，使用ctrl+alt+DD,没有缩进量。十分low B.

**Comment by 1824437** [comment]
如果不预先留个空行，使用ctrl+alt+DD会把上一行代码替换掉。十分low b.

**Comment by TheOpenDevProject** [comment]
We do not support other language's at this time, sorry about that. Closing issue.

**Comment by kvkens** [comment]
丢人现眼
