### ISSUE TITLE
Support to doc functions as properties

### ISSUE THREAD

**Issue by michaeljota** [joelday/vscode-docthis#19]
I don't know, maybe related to #15 but, if the function is declared as propertie of an object (I think it's called that way, very sorry if I'm wrong), it does not generate the documentation to that function, but the function outside (?). 

```javascript
/**
     * This it's generated by...
     * 
     * @param $http (description)
     * @param $window (description)
     * @returns (description)
     */
    function SomeNamedFunction($http, $window) {
        return {
            //trying to generate doc on this.
            enter: function (_id) {
                return $resource.enter({id: _id},
                    function (obj) {
                        
                    }, function (err) {
                        
                    }).$promise;
            }
        }
    }
```

Yeah, the code explains better. (I hope)

**Comment by joelday** [comment]
Fixed in 0.2.0.

**Comment by michaeljota** [comment]
Thanks! I'll update.

**Comment by joelday** [comment]
Just made some minor improvements that are related to this, specifically arrow functions not being included and @returns being added improperly.
