### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by JulioC** [joelday/vscode-docthis#222]
Some statistics:
- Lastest version 0.7.1 was [released o June 2018](https://github.com/joelday/vscode-docthis/commit/c3a7cb764290904d923c9c8913a3243b252a5c46)
- Last real issue was closed on October 2019
- Last commit on February 2019
- Version 0.7.2 is on holding on big features (arrow functions)

Does anyone have any info on the situation? Is there any good alternatives to it?

**Comment by TheOpenDevProject** [comment]
The project is not officially anything at the moment. @joelday I believe just got super busy but we're taking pull requests and at some point Ill get back into it.

**Comment by JulioC** [comment]
That's very nice to know! Thanks for the update!

**Comment by JulioC** [comment]
Is there any planned date for the next release to the marketplace?
