### ISSUE TITLE
Support C/C++ syntax

### ISSUE THREAD

**Issue by csholmq** [joelday/vscode-docthis#26]
Just like https://atom.io/packages/docblockr (based on https://github.com/spadgos/sublime-jsdocs) it would be nice if you could support other programming languages but JS/TS.

**Comment by joelday** [comment]
TBH, a docblockr vscode port is probably a good idea.

**Comment by joelday** [comment]
The main difference is that docthis uses the language service for static analysis. Once that uses the type checker, that'll get even better for JavaScript.

**Comment by csholmq** [comment]
So since there only exist syntax highlighting for e.g. C++, does that mean it's currently out of the scope?

**Comment by joelday** [comment]
I'm looking at a long term multi IDE and multi language strategy. In this scenario, each language can use whatever analysis strategy it wants. It's just difficult to put time toward it currently.

**Comment by csholmq** [comment]
Sounds neat. Perhaps a general npm package?

**Comment by joelday** [comment]
Related to #6

**Comment by cameronwp** [comment]
👍

**Comment by TheOpenDevProject** [comment]
@joelday I do believe VSCode now supports many more languages with the static analyser

**Comment by BillDenton** [comment]
+1 Would be a great addition for C and C++. Thanks.

**Comment by joelday** [comment]
Please see https://github.com/joelday/vscode-docthis/issues/196! Thank you!
