### ISSUE TITLE
Documenting via typing '/**' doesn't indent the comment properly

### ISSUE THREAD

**Issue by Elarcis** [joelday/vscode-docthis#31]
When documenting a JS function via` /**`, the comment created isn't indented properly, whereas `Ctrl+Alt+D` works as expected.

It should be noted that I'm not using any format-altering extension besides `compulim-vscode-closetag`.

I only have changed one option regarding file formatting:

`"files.trimTrailingWhitespace": true`

![code_2016-06-21_08-28-17](https://cloud.githubusercontent.com/assets/990841/16219998/48222f62-378a-11e6-8c4f-ae9c5779cce7.png)

**Comment by joelday** [comment]
Ah, bummer. This is why you don't add major features while spaced out and fighting a cold. Thank you for the very thorough bug.

Does this only repro in .js/.jsx files? Thank you!

**Comment by joelday** [comment]
Fixed in 0.3.1.

**Comment by Elarcis** [comment]
Oh, I was gonna do more tests and answer you D:

Glad it was easy to fix! Good job!
