### ISSUE TITLE
Enhancement: When inserting documentation, put the cursor at the line where description will be put

### ISSUE THREAD

**Issue by Elarcis** [joelday/vscode-docthis#32]
Currently, when we insert a doc comment, the cursor is kept where it were when we did the shortcut (or typed `/**`), relatively to the documented element.

As we usually want to write the doc right after we inserted it, would it be feasible, and relevant, to automatically move the cursor inside of the comment, where the description goes, so we get a more fluent documentation workflow?

**Comment by joelday** [comment]
Lost track of this one. This got added a while back. :)
