### ISSUE TITLE
Properly generate docs for `export const` arrow functions.

### ISSUE THREAD

**Issue by janhartmann** [joelday/vscode-docthis#34]
Thanks for this extension, it's a lifesaver for good documentation.

I was wondering if it possible to extend the behavior to document function such as:

``` js
export const hexToRgba = (hex, opacity = 1) => {
    var shorthandRegex = /^#?([a-f\d])([a-f\d])([a-f\d])$/i;
    hex = hex.replace(shorthandRegex, function(m, r, g, b) {
        return r + r + g + g + b + b;
    });
    var result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
    return result ? [parseInt(result[1], 16), parseInt(result[2], 16), parseInt(result[3], 16), opacity] : null;
};
```

Thanks a lot! :-)

**Comment by TheOpenDevProject** [comment]
should be possible. The problem is that arrow notation is support seems to be broken or at least limited in the scope its recognised in. From my testing I could not get it to document any kind of arrow function.

**Comment by Xananax** [comment]
Maybe a minor difference, but I use one function per file and use `export default`, eg:

```js
export default (thing:any) => () => thing
``` 

If that could be supported too, it'd be swell!

**Comment by joelday** [comment]
@Xananax that has been getting on my nerves, too. :)

**Comment by jamesone** [comment]
Any update on this issue? Would be awesome if this were possible!!

**Comment by joelday** [comment]
Tracking this with #178
