### ISSUE TITLE
Exception thrown in 'Document Everything': returnNode.getChildren is not a function

### ISSUE THREAD

**Issue by Elric-pp** [joelday/vscode-docthis#37]
Platform: darwin

Exception:
[object Object]

Steps to reproduce the error:
CTRL + ALT + D, CTRL + ALT + E

Code to reproduce error (optional):

> In a normal js file, maybe there is nothing to document, but it should not to be an error

```
var raw = require('raw-socket')
var socket = raw.createSocket ({protocol: raw.Protocol.None});

socket.on ("message", function (buffer, source) {
    console.log ("received " + buffer.length + " bytes from " + source);
});

```

**Comment by joelday** [comment]
Can't repro this now. :)
