### ISSUE TITLE
Exception thrown in 'Document This': Cannot read property 'getText' of undefined

### ISSUE THREAD

**Issue by toto42** [joelday/vscode-docthis#42]
Hey,
I just installed you plugin, it looks cool, but I ran into a small bug.
If you try to document a class that has no name like `export default class {...}` it breaks.
Maybe the solution would be either let the `@class` empty and let the dev do whatever or default it to `default` or even better take the file name?

Thanks for your work! :)

Platform: darwin

Exception:
[object Object]

Steps to reproduce the error:
Trying to document an anonymous class.

Code to reproduce error (optional):
`export default class {...}`

**Comment by joelday** [comment]
Tracking this in #53
