### ISSUE TITLE
Like automaticForBlockComments but after Enter key

### ISSUE THREAD

**Issue by Avol-V** [joelday/vscode-docthis#44]
It would be great, if you add option like `automaticForBlockComments` but that works after pressing Enter key (adding new line after `/**`), like it works in some other editors, for easily adding single-line comment:

``` ts
/** My description */
const myVar = 1;
```

**Comment by 19majkel94** [comment]
+10000000
I document public class field with one-line comments and I need this type of settings too!
Could you do it, @joelday ?

**Comment by joelday** [comment]
Thanks! I absolutely agree that it should handle it this way.

**Comment by TheOpenDevProject** [comment]
Ill take this one as well.
