### ISSUE TITLE
leverage hungarian notation for type inference

### ISSUE THREAD

**Issue by dominikschreiber** [joelday/vscode-docthis#49]
Some projects use hungarian notation variable names (e.g. `aFoo` is an array, `iBar` is an int/number) to convey basic type information. This type information can easily be extracted to provide better type guesses than `{any}`.

E.g:

```javascript
function mapPolyfill(aItems, fMap) {
  var aResult;
  if (typeof aItems.map === 'function') {
    return aItems.map(fMap);
  } else {
    for (var i = 0; i < aItems.length; i++) {
      aResult.push(fMap(aItems[i]));
    }
    return aResult;
  }
}
```

could get a generated JSDoc of

```javascript
/**
 * @param {Array} aItems
 * @param {function} fMap
 */
```

if one used the information given by the hungarian notation.

It would be advisable to make this optional, e.g. behind a configuration option like `docthis.enableHungarianNotationEvaluation` (defaulting to `false` for backwards compatibility).

I'd be happy to work on this issue and submit a pull request if this is a generally accepted feature.

**Comment by TheOpenDevProject** [comment]
While I am not opposed to making somewhat ambiguous guesses we would for sure want it turned off by default. Please do have a crack at it and submit a PR. I will happily review your PR and @joelday will also review it as he has the final say.

**Comment by TheOpenDevProject** [comment]
Implemented. See #50
