### ISSUE TITLE
Consider babylon as an optional API to quickly support ES6 functionality

### ISSUE THREAD

**Issue by TheOpenDevProject** [joelday/vscode-docthis#51]
I think we should consider adding this into the pipeline if native ES6 code is being used as it wil give us clean acess to destructured parameters and arrow functions in all contexts.

Open for discussion.

https://github.com/babel/babylon

**Comment by joelday** [comment]
Luckily the TypeScript has filled in most of the ES6 gaps, I believe. Can always reevaluate.
