### ISSUE TITLE
Semver

### ISSUE THREAD

**Issue by joelday** [joelday/vscode-docthis#54]
We haven't been conforming to this standard. Would probably be a good idea to start. Let's rev the minor version when we add features, even if they're tiny.

**Comment by TheOpenDevProject** [comment]
Are you wanting to Semver the whole repo or the code?. Eg when a new commit is made even if its docs or doc cleanup or just when code changes?

**Comment by joelday** [comment]
@TheOpenDevProject Just how we rev the version number per release.

**Comment by TheOpenDevProject** [comment]
Alright noted.
