### ISSUE TITLE
Suggestion: add @deprecated tag

### ISSUE THREAD

**Issue by nomaed** [joelday/vscode-docthis#55]
_Edited: My original suggestion was adding a more complex support but I realize it is out of this plugin's scope, so there's a small suggestion instead_

Sometimes it could be very helpful to deprecate an identifier with a shortcut.
So I suggest adding a support for the tag `@deprecated` and having an option to "Deprecate this!".

**Comment by nomaed** [comment]
I mean something similar to `^⌥D ^⌥D` "trick". But except of generating a full jsDoc block, just generating a `/** @deprecated <description> */` block.

This is quite minor, so feel free to close the issue if you don't feel this worths the investment.

**Comment by TheOpenDevProject** [comment]
@nomaed I am not sure if those characters are not rendering properly for me but I think I get you. Ill add this to our next release.

**Comment by joelday** [comment]
I think this is fine, but I suspect that there are some other extensibility points we should look at for 1.0 such as code completion, etc. where this might fit better.
