### ISSUE TITLE
Exception thrown in 'Document This': Cannot read property 'getText' of undefined

### ISSUE THREAD

**Issue by Mixalloff** [joelday/vscode-docthis#57]
Platform: linux

Steps to reproduce the error:

Code excerpt that reproduces the error (optional):

Exception:
{"name":"TypeError","message":"Cannot read property 'getText' of undefined","stack":"TypeError: Cannot read property 'getText' of undefined\n    at Documenter._emitClassDeclaration (/home/mikhail/.vscode/extensions/joelday.docthis-0.3.5/out/src/documenter.js:240:44)\n    at Documenter._documentNode (/home/mikhail/.vscode/extensions/joelday.docthis-0.3.5/out/src/documenter.js:186:22)\n    at Documenter.documentThis (/home/mikhail/.vscode/extensions/joelday.docthis-0.3.5/out/src/documenter.js:56:32)\n    at /home/mikhail/.vscode/extensions/joelday.docthis-0.3.5/out/src/extension.js:105:24\n    at runCommand (/home/mikhail/.vscode/extensions/joelday.docthis-0.3.5/out/src/extension.js:62:9)\n    at /home/mikhail/.vscode/extensions/joelday.docthis-0.3.5/out/src/extension.js:104:9\n    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:13:23492\n    at e.edit (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:12:16971)\n    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:13:23458\n    at t.$executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:11:26442)"}

**Comment by joelday** [comment]
@Mixalloff Let me know if you see this again in 0.3.9. Thanks!
