### ISSUE TITLE
Language and documentation format agnostic architecture

### ISSUE THREAD

**Issue by joelday** [joelday/vscode-docthis#6]
Would be ideal to be able to use the same "Document This" command for other languages such as C#.

**Comment by csholmq** [comment]
+1 :+1:

**Comment by joelday** [comment]
Related to #12

**Comment by jackvial** [comment]
Would love to see this extension support PHP.

**Comment by antoligy** [comment]
Hey, anything that can be done to move this forward?  Any ideas on how this could be contributed?

**Comment by joelday** [comment]
@antoligy Starting a major refactor today to support multiple languages and editors. Will open this up as soon as the basics are in.

**Comment by antoligy** [comment]
Awesome, best of luck @joelday!

**Comment by TheOpenDevProject** [comment]
I should probably stop being lazy and help out :smile: but yea I plan on making this happen with joel.

**Comment by jens1o** [comment]
Would like to have it also available for php. I would help you with the integration if you say what I need to do.

**Comment by felipetoffolo1** [comment]
@joelday when the refactor is done, i can contribute with PHP support

**Comment by evanwarner** [comment]
Yes please! I use the JSDoc syntax for longer comments in CSS files. Even just the auto insertion of ` * ` on new lines as I type would be marvelous.
