### ISSUE TITLE
Exception thrown in 'Document This': Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by jorgecasar** [joelday/vscode-docthis#61]
Platform: darwin

Steps to reproduce the error:
Try to document a Polymer Component like:

```
(function() {
  'use strict';
  Polymer({
    is: 'glomo-access-manager',
    properties: {
        param1: {
          type: String,
          value: 'myParam'
        },
    },
    method: function(param, param2){
      //Code here
    }
  });
}());
```

Code excerpt that reproduces the error (optional):

Exception:
{"name":"TypeError","message":"Cannot read property 'find' of undefined","stack":"TypeError: Cannot read property 'find' of undefined\n    at Documenter._emitPropertyDeclaration (/Users/jorgecasar/.vscode/extensions/joelday.docthis-0.3.5/out/src/documenter.js:250:50)\n    at Documenter._documentNode (/Users/jorgecasar/.vscode/extensions/joelday.docthis-0.3.5/out/src/documenter.js:192:22)\n    at Documenter.documentThis (/Users/jorgecasar/.vscode/extensions/joelday.docthis-0.3.5/out/src/documenter.js:56:32)\n    at /Users/jorgecasar/.vscode/extensions/joelday.docthis-0.3.5/out/src/extension.js:105:24\n    at runCommand (/Users/jorgecasar/.vscode/extensions/joelday.docthis-0.3.5/out/src/extension.js:62:9)\n    at /Users/jorgecasar/.vscode/extensions/joelday.docthis-0.3.5/out/src/extension.js:104:9\n    at /opt/homebrew-cask/Caskroom/visual-studio-code/1.0.0,fa6d0f03813dfb9df4589c30121e9fcffa8a8ec8/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:13:23492\n    at e.edit (/opt/homebrew-cask/Caskroom/visual-studio-code/1.0.0,fa6d0f03813dfb9df4589c30121e9fcffa8a8ec8/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:12:16971)\n    at /opt/homebrew-cask/Caskroom/visual-studio-code/1.0.0,fa6d0f03813dfb9df4589c30121e9fcffa8a8ec8/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:13:23458\n    at t.$executeContributedCommand (/opt/homebrew-cask/Caskroom/visual-studio-code/1.0.0,fa6d0f03813dfb9df4589c30121e9fcffa8a8ec8/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:11:26442)\n    at t.e.handle (/opt/homebrew-cask/Caskroom/visual-studio-code/1.0.0,fa6d0f03813dfb9df4589c30121e9fcffa8a8ec8/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:11:11474)\n    at s (/opt/homebrew-cask/Caskroom/visual-studio-code/1.0.0,fa6d0f03813dfb9df4589c30121e9fcffa8a8ec8/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:8:2033)\n    at p (/opt/homebrew-cask/Caskroom/visual-studio-code/1.0.0,fa6d0f03813dfb9df4589c30121e9fcffa8a8ec8/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:8:2710)\n    at _combinedTickCallback (internal/process/next_tick.js:67:7)\n    at process._tickCallback (internal/process/next_tick.js:98:9)"}

**Comment by joelday** [comment]
@jorgecasar This should be fixed now.
