### ISSUE TITLE
Trying to document a member function jumps to class

### ISSUE THREAD

**Issue by ghost** [joelday/vscode-docthis#62]
When I have the following:
```javascript
var docthis;
(function (docthis) {
    var test = (function () {
        function test() { }

        test.greet = function(){
            return "Hello, World";
        };
        
        return test;
    })();
    docthis.test = test;
})(docthis || (docthis = {}));
```
and I want to use "Document This" on test.greet it jumps up to test.

**Comment by TheOpenDevProject** [comment]
Inline functions are quite sketchy and are only "supported" as a consequence of other code rather than this actually being supported. We probably need to rethink this as a lot of people have been asking how to document inline functions. What happens if you use document in place.
