### ISSUE TITLE
Linux + shortcuts

### ISSUE THREAD

**Issue by Bugpatchcrashdebugging** [joelday/vscode-docthis#63]
How to change key binding, in Xfce alt + ctr + D hide all windows.

**Comment by TheOpenDevProject** [comment]
Are you asking about our VSCode addin or XFCE?.

**Comment by joelday** [comment]
@Bugpatchcrashdebugging You can change it in your VSCode settings. Can you please suggest an alternative that won't conflict with anything? Thanks!
