### ISSUE TITLE
Clear current jsdocs before "Document Everything" to allow updated jsdocs.

### ISSUE THREAD

**Issue by rylphs** [joelday/vscode-docthis#64]
If you call "document everything" twice the jsdocs are also added twice. That would be good if it cleared all jsdocs before doing that. So, for example, if you later add some method, or change its parameters you can just call "document everything" again and the jsdoc will be updated.

**Comment by jnachtigall** [comment]
I don't think clearing the current jsdocs is best, because I usually annotate (describe) the paramters also. That is it should rather be updated:

For instance for:
```
   * @param {number} [fromTop=50] - the offset when shrinkedClassToggle should be added
```

Clear everything left of the hyphen (`-`) and keep everything right of it. This way updating would be painless.

**Comment by joelday** [comment]
#66
