### ISSUE TITLE
Exception thrown in 'Document Everything': Cannot read property 'getText' of undefined

### ISSUE THREAD

**Issue by Harris-Aaron** [joelday/vscode-docthis#65]
Platform: darwin

Steps to reproduce the error:

Code excerpt that reproduces the error (optional):

Exception:
{"name":"TypeError","message":"Cannot read property 'getText' of undefined","stack":"TypeError: Cannot read property 'getText' of undefined\n    at Documenter._emitClassDeclaration (/Users/harris-aaron/.vscode/extensions/joelday.docthis-0.3.5/out/src/documenter.js:240:44)\n    at Documenter._documentNode (/Users/harris-aaron/.vscode/extensions/joelday.docthis-0.3.5/out/src/documenter.js:186:22)\n    at /Users/harris-aaron/.vscode/extensions/joelday.docthis-0.3.5/out/src/documenter.js:82:37\n    at Array.forEach (native)\n    at Documenter.documentEverything (/Users/harris-aaron/.vscode/extensions/joelday.docthis-0.3.5/out/src/documenter.js:80:22)\n    at /Users/harris-aaron/.vscode/extensions/joelday.docthis-0.3.5/out/src/extension.js:111:24\n    at runCommand (/Users/harris-aaron/.vscode/extensions/joelday.docthis-0.3.5/out/src/extension.js:62:9)\n    at /Users/harris-aaron/.vscode/extensions/joelday.docthis-0.3.5/out/src/extension.js:110:9\n    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:12:16738\n    at e.edit (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:11:14547)\n    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:12:16704\n    at t.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:10:19835)\n    at t.e.handle (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:10:4203)\n    at s (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:7:11178)\n    at p (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:7:11855)\n    at _combinedTickCallback (internal/process/next_tick.js:67:7)\n    at process._tickCallback (internal/process/next_tick.js:98:9)"}

**Comment by joelday** [comment]
@Harris-Aaron Let me know if this issue persists in 0.3.9. Thanks!
