### ISSUE TITLE
Exception thrown in 'Document This': Could not find file: 'e:/Workspace/Eclipse_Neon_4.6.2_JavaEE/shushan/src/main/webapp/_static/app/process/bgMine.js'.

### ISSUE THREAD

**Issue by chliuqi** [joelday/vscode-docthis#71]
Platform: win32

Steps to reproduce the error:

Code excerpt that reproduces the error (optional):

Exception:
{"name":"Error","message":"Could not find file: 'e:/Workspace/Eclipse_Neon_4.6.2_JavaEE/shushan/src/main/webapp/_static/app/process/bgMine.js'.","stack":"Error: Could not find file: 'e:/Workspace/Eclipse_Neon_4.6.2_JavaEE/shushan/src/main/webapp/_static/app/process/bgMine.js'.\n    at getValidSourceFile (C:\\Users\\hasee\\.vscode\\extensions\\joelday.docthis-0.3.7\\node_modules\\typescript\\lib\\typescript.js:78776:23)\n    at Object.getSyntacticDiagnostics (C:\\Users\\hasee\\.vscode\\extensions\\joelday.docthis-0.3.7\\node_modules\\typescript\\lib\\typescript.js:78983:52)\n    at Documenter._getSourceFile (C:\\Users\\hasee\\.vscode\\extensions\\joelday.docthis-0.3.7\\out\\src\\documenter.js:176:24)\n    at Documenter.documentThis (C:\\Users\\hasee\\.vscode\\extensions\\joelday.docthis-0.3.7\\out\\src\\documenter.js:46:33)\n    at runCommand (C:\\Users\\hasee\\.vscode\\extensions\\joelday.docthis-0.3.7\\out\\src\\extension.js:110:24)\n    at runCommand (C:\\Users\\hasee\\.vscode\\extensions\\joelday.docthis-0.3.7\\out\\src\\extension.js:66:9)\n    at context.subscriptions.push.vs.commands.registerTextEditorCommand (C:\\Users\\hasee\\.vscode\\extensions\\joelday.docthis-0.3.7\\out\\

**Comment by joelday** [comment]
@chliuqi Let me know if this still happens in 0.3.8. It might take a few minutes before it shows up in the extension browser.
