### ISSUE TITLE
Document This Causing Incorrect HTML Comments

### ISSUE THREAD

**Issue by Tsmith18256** [joelday/vscode-docthis#79]
When I have Document This installed and press Ctrl-/ on a block of highlighted text in an HTML file, it is causing the block to be surrounded with `{#` and `#}`, instead of the proper `<!--` and `-->`.

**Comment by joelday** [comment]
Couldn't reproduce this. Can you try disabling other extensions? It might be a conflict?

**Comment by joelday** [comment]
@Tsmith18256 Just pinging you real quick. Thanks!

**Comment by Tsmith18256** [comment]
@joelday Hmmm, well this is weird. I disabled DocThis last week and the problem went away instantly, but now it seems to have come back. I guess it is another extension and maybe it just hadn't loaded yet when I tested it last week. Either way something went wrong there and I'll have to track down what extension is really causing the problem.

Sorry about the confusion!

**Comment by joelday** [comment]
Weird! Well, let me know if you hit this again.

**Comment by Tsmith18256** [comment]
Just found the real culprit.. It was the TWIG Pack plugin. The weird comments I'm seeing are from the comment syntax for TWIG files, but for some reason it's impacting the HTML. Thanks for the help!
