### ISSUE TITLE
Exception thrown in 'Document This': Could not find file: 'Untitled-1'.

### ISSUE THREAD

**Issue by andrewjrvs** [joelday/vscode-docthis#91]
Platform: win32

Steps to reproduce the error:
Try to run Document This (Ctrl-Alt-D + Ctrl-Alt-D) on a New File which is unsaved. 

1. Create New File [(file -> New File) or (Ctrl + N)]
2. Change Language to JavaScript [(Ctrl+K M) select JavaScript)]
3. Add a function ["function helloWorld(){}"]
4. Run Document This (Ctrl-Alt-D + Ctrl-Alt-D) 

Code excerpt that reproduces the error (optional):

Exception:
{"name":"Error","message":"Could not find file: 'Untitled-1'.","stack":"Error: Could not find file: 'Untitled-1'.\n    at getValidSourceFile (C:\\Users\\Andrew\\.vscode\\extensions\\joelday.docthis-0.3.10\\node_modules\\typescript\\lib\\typescript.js:78776:23)\n    at Object.getSyntacticDiagnostics (C:\\Users\\Andrew\\.vscode\\extensions\\joelday.docthis-0.3.10\\node_modules\\typescript\\lib\\typescript.js:78983:52)\n    at Documenter._getSourceFile (C:\\Users\\Andrew\\.vscode\\extensions\\joelday.docthis-0.3.10\\out\\src\\documenter.js:180:24)\n    at Documenter.documentThis (C:\\Users\\Andrew\\.vscode\\extensions\\joelday.docthis-0.3.10\\out\\src\\documenter.js:49:33)\n    at runCommand (C:\\Users\\Andrew\\.vscode\\extensions\\joelday.docthis-0.3.10\\out\\src\\extension.js:110:24)\n    at runCommand (C:\\Users\\Andrew\\.vscode\\extensions\\joelday.docthis-0.3.10\\out\\src\\extension.js:66:9)\n    at context.subscriptions.push.vs.commands.registerTextEditorCommand (C:\\Users\\Andrew\\.vscode\\extensions\\joelday.docthis-0.3.10\\out\\src\\extension.js:109:9)\n    at c:\\Program Files (x86)\\Microsoft VS Code\\resources\\app\\out\\vs\\workbench\\node\\extensionHostProcess.js:14:22263\n    at e.edit (c:\\Program Files (x86)\\Microso

**Comment by joelday** [comment]
Fixed in 0.3.11.
