### ISSUE TITLE
Exception thrown in 'Document Everything': Could not find file: '/var/www/seekr/app/assets/javascripts/app/midias/controllers/midiascontroller.es6'.

### ISSUE THREAD

**Issue by brunocechet** [joelday/vscode-docthis#92]
Platform: linux

Steps to reproduce the error: I just try to generate the documentation.
Tip: - the file name is cameCase, the filename in the log is incorrect
       - I use ctrl + shift + P shortcurt

Code excerpt that reproduces the error (optional):

Exception:
{"name":"Error","message":"Could not find file: '/var/www/seekr/app/assets/javascripts/app/midias/controllers/midiascontroller.es6'.","stack":"Error: Could not find file: '/var/www/seekr/app/assets/javascripts/app/midias/controllers/midiascontroller.es6'.\n    at getValidSourceFile (/home/brunocechet/.vscode/extensions/joelday.docthis-0.3.10/node_modules/typescript/lib/typescript.js:78776:23)\n    at Object.getSyntacticDiagnostics (/home/brunocechet/.vscode/extensions/joelday.docthis-0.3.10/node_modules/typescript/lib/typescript.js:78983:52)\n    at Documenter._getSourceFile (/home/brunocechet/.vscode/extensions/joelday.docthis-0.3.10/out/src/documenter.js:180:24)\n    at Documenter.documentEverything (/home/brunocechet/.vscode/extensions/joelday.docthis-0.3.10/out/src/documenter.js:78:31)\n    at runCommand (/home/brunocechet/.vscode/extensions/joelday.docthis-0.3.10/out/src/extension.js:116:24)\n    at runCommand (/home/brunocechet/.vscode/extensions/joelday.docthis-0.3.10/out/src/extension.js:66:9)\n    at context.subscriptions.push.vs.commands.registerTextEditorCommand (/home/brunocechet/.vscode/extensions/joelday.docthis-0.3.10/out/src/extension.js:115:9)\n    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:14:22263\n    at e.edit (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:13:14855)\n    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:14:22229\n    at t.$executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:12:19624)\n    at t.e.handle (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:12:2729)\n    at s (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:8:15667)\n    at d (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:8:16344)\n    at _combinedTickCallback (internal/process/next_tick.js:67:7)\n    at process._tickCallback (internal/process/next_tick.js:98:9)"}

**Comment by joelday** [comment]
Fixed in 0.3.11.
