### ISSUE TITLE
Exception thrown in 'Document This': Could not find file: '/var/www/seekr/app/assets/javascripts/app/midias/controllers/midiascontroller.es6'.

### ISSUE THREAD

**Issue by brunocechet** [joelday/vscode-docthis#95]
Platform: linux

Steps to reproduce the error:

Code excerpt that reproduces the error (optional):

Exception:
{"name":"Error","message":"Could not find file: '/var/www/seekr/app/assets/javascripts/app/midias/controllers/midiascontroller.es6'.","stack":"Error: Could not find file: '/var/www/seekr/app/assets/javascripts/app/midias/controllers/midiascontroller.es6'.\n    at getValidSourceFile (/home/brunocechet/.vscode/extensions/joelday.docthis-0.3.10/node_modules/typescript/lib/typescript.js:78776:23)\n    at Object.getSyntacticDiagnostics (/home/brunocechet/.vscode/extensions/joelday.docthis-0.3.10/node_modules/typescript/lib/typescript.js:78983:52)\n    at Documenter._getSourceFile (/home/brunocechet/.vscode/extensions/joelday.docthis-0.3.10/out/src/documenter.js:180:24)\n    at Documenter.documentThis (/home/brunocechet/.vscode/extensions/joelday.docthis-0.3.10/out/src/documenter.js:49:33)\n    at runCommand (/home/brunocechet/.vscode/extensions/joelday.docthis-0.3.10/out/src/extension.js:110:24)\n    at runCommand (/home/brunocechet/.vscode/extensions/joelday.docthis-0.3.10/out/src/extension.js:66:9)\n    at context.subscriptions.push.vs.commands.registerTextEditorCommand (/home/brunocechet/.vscode/extensions/joelday.docthis-0.3.10/out/src/extension.js:109:9)\n    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:12:16738\n    at e.edit (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:11:14547)\n    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:12:16704\n    at t.$executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:10:19835)\n    at t.e.handle (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:10:4203)\n    at s (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:7:11178)\n    at p (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:7:11855)\n    at _combinedTickCallback (internal/process/next_tick.js:67:7)\n    at process._tickCallback (internal/process/next_tick.js:98:9)"}

**Comment by joelday** [comment]
Fixed in 0.3.11.
